name: battleborn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52976
title: Performance Perfect is Perfect Performance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.925216160248965
  lightness: 0.31320717791095376
  saturation: 0.396369312889874
  rhythmicContrast: 0.8157298334408551
purpose: []
