name: battleborn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52976
title: Performance Perfect is Perfect Performance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3d3d3'
    - '#969696'
    - '#24160d'
    - '#ec1b23'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
