name: battleborn
favicon: null
layout_spectrum: 0.50176
typography_spectrum: 0.52694
title: battleborn.me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b5881'
    - '#001334'
    - '#597f93'
    - '#fefefe'
    - '#c1d1d0'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
